tap 'caskroom/homebrew-cask'
brew 'cask'

# cli
cask 'iterm2'

# emacs
tap 'railwaycat/emacsmacport'
brew 'emacs-mac', args: ['with-spacemacs-icon']

# atom
cask 'atom'

# python (must come before *vim)
brew 'python'

# useful utilities
cask 'cheatsheet'
cask 'dropbox'
cask 'rescuetime'

# Android
cask 'android-file-transfer'

# Browser
cask 'google-chrome'

# Chat
cask 'skype'

# Gaems
cask 'steam'

# Haskell
cask 'haskell-platform'

# Go
brew 'go'

# CTF
brew 'aircrack-ng'
brew 'dex2jar'
brew 'dns2tcp'
brew 'ettercap', args: ['with-gtk+']
brew 'hydra'
brew 'john'
brew 'nmap'
brew 'socat'
brew 'tcpflow'
brew 'tcpreplay'
brew 'tcptrace'
brew 'ucspi-tcp' # `tcpserver` etc.

# OVPN
cask 'tunnelblick'

# HAX
brew 'youtube-dl'

# VIRTUALIZATION
cask 'virtualbox'
cask 'vagrant'
cask 'boot2docker'

# MUSIC/MEDIA
cask 'mpv'
cask 'mediainfo'
cask 'audacity'
cask 'xld'

# AVIATION
brew 'rtl-sdr'

