tap 'caskroom/homebrew-cask'
brew 'cask'

# gnu
brew 'coreutils'
brew 'moreutils'
brew 'findutils'
brew 'htop-osx'
brew 'unrar'
brew 'wget', args: ['with-iri']
brew 'ack'
brew 'git'
brew 'lynx'
brew 'pv'
brew 'tree'

# cli
brew 'grc'
brew 'spark'
cask 'iterm2'

# remote
brew 'mobile-shell'

# vim
brew 'vim', args: ['override-system-vi']

# maintenence
cask 'the-unarchiver'
cask 'disk-inventory-x'
cask 'appcleaner'

# useful utilities
cask 'cheatsheet'
cask 'dropbox'
brew 'encfs'

# Android
cask 'android-file-transfer'

# Browser
cask 'google-chrome'

# Chat
cask 'skype'

# Gaems
cask 'steam'

# Haskell
cask 'haskell-platform'

# Go
brew 'go'

# CTF
brew 'aircrack-ng'
brew 'bfg'
brew 'binutils'
brew 'binwalk'
brew 'cifer'
brew 'dex2jar'
brew 'dns2tcp'
brew 'ettercap', args: ['with-gtk+']
brew 'fcrackzip'
brew 'foremost'
brew 'hashpump'
brew 'hydra'
brew 'john'
brew 'knock'
brew 'nmap'
brew 'pngcheck'
brew 'socat'
brew 'sqlmap'
brew 'tcpflow'
brew 'tcpreplay'
brew 'tcptrace'
brew 'ucspi-tcp' # `tcpserver` etc.
brew 'xz'

# OVPN
cask 'tunnelblick'

# HAX
brew 'youtube-dl'
brew 'terminal-notifier'

# VIRTUALIZATION
cask 'virtualbox'
cask 'vagrant'
cask 'boot2docker'

# LATEX
cask 'mactex'

# MUSIC/MEDIA
cask 'mpv'
cask 'mediainfo'
cask 'audacity'
cask 'xld'

# AVIATION
brew 'rtl-sdr'

